x-fern-pagination:
  cursor: $request.pageToken
  next_cursor: $response.nextPageToken
  results: $response.results
paths:
  /v1/organizations/search:
    get:
      x-fern-sdk-group-name:
        - organizations
      x-fern-sdk-method-name: search
  /v1/organizations/{id}:
    get:
      x-fern-sdk-group-name:
        - organizations
      x-fern-sdk-method-name: get
  /v1/connects:
    post:
      x-fern-sdk-group-name:
        - connects
      x-fern-sdk-method-name: create
  /v1/connects/{id}:
    get:
      x-fern-sdk-group-name:
        - connects
      x-fern-sdk-method-name: get
  /v1/grants:
    get:
      x-fern-pagination: true
      x-fern-sdk-group-name:
        - grants
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - grants
      x-fern-sdk-method-name: create
  /v1/grants/{id}:
    get:
      x-fern-sdk-group-name:
        - grants
      x-fern-sdk-method-name: get
  /v1/recurring_grants:
    get:
      x-fern-pagination: true
      x-fern-sdk-group-name:
        - recurring_grants
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - recurring_grants
      x-fern-sdk-method-name: create
  /v1/recurring_grants/{id}:
    get:
      x-fern-sdk-group-name:
        - recurring_grants
      x-fern-sdk-method-name: get
  /v1/unintegrated_grants:
    get:
      x-fern-pagination: true
      x-fern-sdk-group-name:
        - unintegrated_grants
      x-fern-sdk-method-name: list
  /v1/unintegrated_grants/{id}:
    get:
      x-fern-sdk-group-name:
        - unintegrated_grants
      x-fern-sdk-method-name: get
  /v1/dafs:
    get:
      x-fern-pagination: true
      x-fern-sdk-group-name:
        - donorAdvisedFunds
      x-fern-sdk-method-name: list
  /v1/dafs/{id}:
    get:
      x-fern-sdk-group-name:
        - donorAdvisedFunds
      x-fern-sdk-method-name: get
  /v1/events:
    get:
      x-fern-pagination:
        cursor: $request.cursor
        next_cursor: $response.nextPageToken
        results: $response.results
      x-fern-sdk-group-name:
        - events
      x-fern-sdk-method-name: list
  /v1/events/{id}:
    get:
      x-fern-sdk-group-name:
        - events
      x-fern-sdk-method-name: get
  /v1/event_subscriptions:
    get:
      x-fern-pagination:
        cursor: $request.cursor
        next_cursor: $response.nextPageToken
        results: $response.results
      x-fern-sdk-group-name:
        - eventSubscriptions
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - eventSubscriptions
      x-fern-sdk-method-name: create
  /v1/event_subscriptions/{id}:
    get:
      x-fern-sdk-group-name:
        - eventSubscriptions
      x-fern-sdk-method-name: get
    patch:
      x-fern-sdk-group-name:
        - eventSubscriptions
      x-fern-sdk-method-name: update
