openapi: 3.0.0
info:
  title: Chariot API
  version: "v1"
  description: The Chariot REST API. Please see https://givechariot.readme.io/reference/overview for more details.
  contact:
    name: Chariot Development Team
    url: https://www.givechariot.com/contact
    email: partners@givechariot.com
  termsOfService: https://www.givechariot.com/legal-nonprofit
servers:
  - url: https://sandboxapi.givechariot.com
    description: Sandbox
  - url: https://api.givechariot.com
    description: Production
paths:
  /v1/nonprofit/{ein}:
    get:
      summary: Get nonprofit by EIN
      description: |-
        Get a nonprofit organization by EIN.
        If the nonprofit does not exist, this returns 404 Not Found status.
        If the nonprofit does not pass our compliance checks, a 422 Unprocessable Content is returned with a reason.
        In the case that the nonprofit does not exist, you can create one by calling the POST /v1/nonprofits API endpoint.
        The EIN should be exactly 9 digits and should not contain any special characters such as dashes.
      operationId: get-nonprofit-by-ein
      tags:
        - Nonprofits
      security:
        - auth0:
            - "read:nonprofits"
  /v1/nonprofits:
    post:
      summary: Create nonprofit
      description: |-
        Create a nonprofit organization account.
        This is useful for integration partners to use after a nonprofit consents to use the Chariot payment option on their donation forms.
        If a nonprofit does not already exist for the EIN, this will return a 201 Created status.
        If a nonprofit already exists for the given EIN on the system, this will return a 200 Created status.
        If the nonprofit does not pass our compliance checks, a 422 Unprocessable Content is returned with a reason.
      operationId: create-nonprofit
      tags:
        - Nonprofits
      security:
        - auth0:
            - "create:nonprofits"
  /v1/nonprofits/{id}:
    get:
      summary: Get nonprofit by ID
      description: |-
        Get a nonprofit organization by ID.
        If the nonprofit does not exist, this returns 404 Not Found status.
      operationId: get-nonprofit-by-id
      tags:
        - Nonprofits
      security:
        - auth0:
            - "read:nonprofits"
  /v1/connects:
    post:
      summary: Create Connect
      description: |-
        Get or create a Connect object. Only one Connect object can be created per Nonprofit for a given Fundraising Application. If one already exists, this will return a 200 status with the existing object. The returned Connect can be used to integrate the client-side Chariot Connect component using the id property (CID) and also query for data generated from the Chariot Connect instance from the Chariot API using the apiKey property.
      operationId: create-connect
      tags:
        - Connects
      security:
        - auth0:
            - "create:connects"
  /v1/connects/{id}:
    get:
      summary: Get Connect
      description: |-
        Get a Connect object with the unique identifier (CID)
      operationId: get-connect
      tags:
        - Connects
      security:
        - auth0:
            - "read:connects"
  /v1/grants:
    get:
      summary: List Grants
      description: |-
        List all grants for the provided API Key. This API allows for paginating over many results.
      operationId: list-grants
      tags:
        - Grants
      security:
        - auth0:
            - "read:grants"
    post:
      summary: Create Grant
      description: |-
        Create a grant from a workflow session. This is useful to capture a grant intent from an authorized connect workflow session and submit the grant request.
        The grant must be captured within 5 minutes of authorization otherwise the request will return status 410 Gone.
        A grant can only be captured once from any given workflow session so any duplicate requests will return status 409 Conflict.
        The grant amount must be in whole dollar increments (rounded to the nearest hundred) as currently DAFs only accept whole dollar grants.
        The grant amount must be greater than or equal to the minimum grant amount for the DAF otherwise the request will return status 400 Bad Request.
        The grant amount must be less than or equal to the user's DAF account balance otherwise the request will return status 400 Bad Request.
      operationId: create-grant
      tags:
        - Grants
      security:
        - auth0:
            - "create:grants"
  /v1/grants/{id}:
    get:
      summary: Get Grant
      description: |-
        Get a grant object generated by Chariot Connect.
        If the grant does not exist, returns a 404 status.
        If the provided ID is not a v4 UUID according to RFC 4122, returns a 400 status.
      operationId: get-grant
      tags:
        - Grants
      security:
        - auth0:
            - "read:grants"
    patch:
      summary: Update Grant
      description: |-
        Update a grant object generated by Chariot Connect.
        This is useful to update the status or acknowledgement of the grant.
        If the grant does not exist, returns a 404 status.
        If the provided ID is not a v4 UUID according to RFC 4122, returns a 400 status.
      operationId: update-grant
      tags:
        - Grants
      security:
        - auth0:
            - "update:grants"
  /v1/unintegrated_grants:
    get:
      summary: List Unintegrated Grants
      description: |-
        List all unintegrated grants for the provided API Key. This API allows for paginating over many results.
      operationId: list-unintegrated-grants
      tags:
        - Grants
      security:
        - auth0:
            - "read:grants"
  /v1/unintegrated_grants/{id}:
    get:
      summary: Get Unintegrated Grant
      description: |-
        Get an unintegrated grant object generated by Chariot Connect.
        If the grant does not exist, returns a 404 status.
        If the provided ID is not a v4 UUID according to RFC 4122, returns a 400 status.
      operationId: get-unintegrated-grant
      tags:
        - Grants
      security:
        - auth0:
            - "read:grants"
    patch:
      summary: Update Unintegrated Grant
      description: |-
        Update an unintegrated grant object generated by Chariot Connect.
        This is useful to update the status or acknowledgement of the unintegrated grant.
        If the unintegrated grant does not exist, returns a 404 status.
        If the provided ID is not a v4 UUID according to RFC 4122, returns a 400 status.
      operationId: update-unintegrated-grant
      tags:
        - Grants
      security:
        - auth0:
            - "update:grants"
  /v1/dafs:
    get:
      summary: List DAFs
      description: List all DAF objects. This API allows for paginating over many results.
      operationId: list-dafs
      tags:
        - DAFs
  /v1/dafs/{id}:
    get:
      summary: Get DAF object
      description: |-
        Get a DAF object by id.
        If the DAF does not exist, returns a 404 status.
        If the provided ID is not a v4 UUID according to RFC 4122, returns a 400 status.
      operationId: get-daf
      tags:
        - DAFs
  /v1/events:
    get:
      summary: List Events
      description: |-
        List all events corresponding to your Chariot account.
      operationId: listEvents
      tags:
        - Events
      security:
        - auth0:
            - "read:events"
  /v1/events/{id}:
    get:
      summary: Retrieve an Event
      description: |-
        Retrieve an event corresponding to your Chariot account.
      operationId: getEvent
      tags:
        - Events
      security:
        - auth0:
            - "read:events"
  /v1/event_subscriptions:
    post:
      summary: Create an Event Subscription
      description: |-
        Create an event subscription corresponding to your Chariot account.
      operationId: createEventSubscription
      tags:
        - Event Subscriptions
      security:
        - auth0:
            - "create:event_subscriptions"
    get:
      summary: List Event Subscriptions
      description: |-
        List all event subscriptions corresponding to your Chariot account.
      operationId: listEventSubscriptions
      tags:
        - Event Subscriptions
      security:
        - auth0:
            - "read:event_subscriptions"
  /v1/event_subscriptions/{id}:
    get:
      summary: Retrieve an Event Subscription
      description: |-
        Retrieve an event subscription corresponding to your Chariot account.
      operationId: getEventSubscription
      tags:
        - Event Subscriptions
      security:
        - auth0:
            - "read:event_subscriptions"
    patch:
      summary: Update an Event Subscription
      description: |-
        Update an event subscription corresponding to your Chariot account.
      operationId: updateEventSubscription
      tags:
        - Event Subscriptions
      security:
        - auth0:
            - "update:event_subscriptions"
components:
  securitySchemes:
    auth0:
      type: oauth2
      description: This API uses OAuth2 with the client credentials flow.
      flows:
        clientCredentials:
          tokenUrl: https://login.givechariot.com/oauth/token
          scopes:
            "create:nonprofits": create a nonprofit and user
            "read:nonprofits": read all nonprofits
            "create:connects": create any connect, principle does not need to be associated with nonprofit
            "read:connects": read all connects for a nonprofit
            "create:grants": create a grant from a workflow session
            "read:grants": "read grants"
            "update:grants": "update grants"
            "read:events": "read events"
            "create:event_subscriptions": "create event subscriptions"
            "read:event_subscriptions": "read event subscriptions"
            "update:event_subscriptions": "update event subscriptions"