openapi: 3.0.0
info:
  title: Chariot API
  version: 'v1'
  description: The Chariot REST API. Please see https://givechariot.readme.io/reference/overview for more details.
  contact:
    name: Chariot Development Team
    url: https://www.givechariot.com/contact
    email: partners@givechariot.com
  termsOfService: https://www.givechariot.com/legal-nonprofit
servers:
  - url: https://sandboxapi.givechariot.com
    description: Sandbox
  - url: https://api.givechariot.com
    description: Production
paths:
  /v1/nonprofit/{ein}:
    get:
      summary: Get nonprofit by EIN
      description: |-
        Get a nonprofit organization by EIN.
        If the nonprofit does not exist, this returns 404 Not Found status.
        In the case that the nonprofit does not exist, you can create one by calling the POST /v1/nonprofits API endpoint.
        The EIN should be exactly 9 digits and should not contain any special characters such as dashes.
      operationId: get-nonprofit-by-ein
      security:
        - auth0:
          - "read:nonprofits"
  /v1/nonprofits:
    post:
      summary: Create nonprofit
      description: |-
        Create a nonprofit organization account.
        This is useful for integration partners to use after a nonprofit consents to use the Chariot payment option on their donation forms.
        If a nonprofit does not already exist for the EIN, this will return a 201 Created status.
        If a nonprofit already exists for the given EIN on the system, this will return a 409 Conflict status.
        When integrating this API, it's useful to either handle the 409 error or make a call to the GET v1/nonprofit/{ein} API first to check if it exists prior to creating it.
      operationId: create-nonprofit
      security:
        - auth0:
          - "create:nonprofits"
  /v1/connects:
    post:
      summary: Create Connect
      description: |-
        Get or create a Connect object. Only one Connect object can be created per Nonprofit-Subscription pair. If one already exists, this will return a 200 status with the existing object. The returned Connect can be used to integrate the client-side Chariot Connect component using the id property (CID) and also query for data generated from the Chariot Connect instance from the Chariot API using the apiKey property.
      operationId: create-connect
      security:
        - auth0:
          - "create:connects"
  /v1/connects/{id}:
    get:
      summary: Get Connect
      description: |-
        Get a Connect object with the unique identifier (CID)
      operationId: get-connect
      security:
        - auth0:
          - "read:connects"
  /v1/grants:
    get:
      summary: List Grants
      description: |-
        List all grants for the provided API Key. This API allows for paginating over many results.
      operationId: list-grants
      security:
        - auth0:
          - "read:grants"
          api_key: []
    post:
      summary: Create Grant
      description: |-
        Create a grant from a workflow session. This is useful to capture a grant intent from an authorized connect workflow session and submit the grant request.
        The grant must be captured within 5 minutes of authorization otherwise the request will return status 410 Gone.
        A grant can only be captured once from any given workflow session so any duplicate requests will return status 409 Conflict.
      operationId: create-grant
      security:
        - auth0:
            - "create:grants"
          api_key: []
  /v1/grants/{id}:
    get:
      summary: Get Grant
      description: |-
        Get a grant object generated by Chariot Connect.
        If the grant does not exist, returns a 404 status.
        If the provided ID is not a v4 UUID according to RFC 4122, returns a 400 status.
      operationId: get-grant
      security:
      - auth0:
        - "read:grants"
        api_key: []
    patch:
      summary: Update Grant
      description: |-
        Update a grant object.
        Currently, this API only supports updating the status of a grant.
        If the grant does not exist, returns a 404 status.
        If the provided ID is not a v4 UUID according to RFC 4122, returns a 400 status.
      operationId: update-grant
      security:
        - auth0:
          - "update:grants"
          api_key: []
  /v1/dafs:
    get:
      summary: List DAFs
      description: List all DAF objects. This API allows for paginating over many results.
      operationId: list-dafs
  /v1/dafs/{id}:
    get:
      summary: Get DAF object
      description: |-
        Get a DAF object by id.
        If the DAF does not exist, returns a 404 status.
        If the provided ID is not a v4 UUID according to RFC 4122, returns a 400 status.
      operationId: get-daf
  /v1/webhooks:
    get:
      summary: List Webhooks
      description: List all Webhooks
      operationId: list-webhooks
      security:
        - auth0:
          - "read:webhooks"
    post:
      summary: Create Webhook
      description: |-
        Creates a Webhook and registers the provided URL endpoint to receive
        HTTP POST webhook messages. The endpoint for the Webhook should be able
        to accept HTTP POST requests. Please see our Webhooks documentation
        for more details.
      operationId: create-webhook
      security:
        - auth0:
          - "create:webhooks"
  /v1/webhooks/{id}:
    get:
      summary: Get Webhook
      description: Get a webhook
      operationId: get-webhook
      security:
        - auth0:
          - "read:webhooks"
    patch:
      summary: Update Webhook
      description: Update a Webhook
      operationId: update-webhook
      security:
        - auth0:
          - "update:webhooks"
    delete:
      summary: Delete Webhook
      description: Delete a Webhook
      operationId: delete-webhook
      security:
        - auth0:
          - "delete:webhooks"
  /v1/webhooks/{id}/test:
    post:
      summary: Test Webhook
      description: Execute a test on a webhook. This will send a test payload to the webhook's endpoint
      operationId: test-webhook
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages:
    get:
      summary: List Webhook Messages
      description: |-
        Lists the Webhook messages for a specific webhook. A message refers to the
        payload sent to your webhook endpoint whenever a specific event occurs.
        Each message represents a discrete event-triggered notification that
        contains relevant data related to the event.
      operationId: list-webhook-messages
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages/{messageId}:
    get:
      summary: Get Webhook Message
      description: |-
        Gets a specific Webhook Message for a specific webhook. A message refers to the
        payload sent to your webhook endpoint whenever a specific event occurs.
        Each message represents a discrete event-triggered notification that
        contains relevant data related to the event.
      operationId: get-webhook-message
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages/{messageId}/resend:
    post:
      summary: Resend Webhook Message
      description: |-
        Resend webhook request for a specific webhook. This does not resend the
        request to all of the original webhooks.
      operationId: resend-message
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages/{messageId}/attempts:
    get:
      summary: List Webhook Message Attempts
      description: Lists the attempts to send a request for a specific message for a specific webhook
      operationId: list-message-attempts
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages/{messageId}/attempts/{attemptId}:
    get:
      summary: Get Webhook Message Attempt
      description: Gets a Webhook Message Attempt for a specific message and webhook.
      operationId: get-webhook-message-attempt
      security:
        - auth0:
          - "read:webhooks"
components:
  securitySchemes:
    auth0:
      type: oauth2
      description: This API uses OAuth2 with the client credentials flow.
      flows:
        clientCredentials:
          tokenUrl: https://login.givechariot.com/oauth/token
          scopes:
            "create:nonprofits": create a nonprofit and user
            "read:nonprofits": read all nonprofits
            "create:connects": create any connect, principle does not need to be associated with nonprofit
            "read:connects": read all connects for a nonprofit
            "create:grants": create a grant from a workflow session
            "read:grants": "read grants"
            "read:webhooks": read all webhooks associated with a subscription
            "create:webhooks": create webhooks for a subscritpion
            "update:webhooks": update all webhooks associated with a subscription
            "delete:webhooks": delete webhooks associated with a subscription
    api_key:
      type: apiKey
      in: header
      name: x-chariot-api-key