openapi: 3.0.0
info:
  title: Chariot Webhooks API
  version: 'v1'
  description: The Chariot Webhooks REST API. Please see https://givechariot.readme.io/reference/webhooks for more details.
  contact:
    name: Chariot Development Team
    url: https://www.givechariot.com/contact
    email: partners@givechariot.com
  termsOfService: https://www.givechariot.com/legal-nonprofit
servers:
  - url: https://sandboxapi.givechariot.com
    description: Sandbox
  - url: https://api.givechariot.com
    description: Production
paths:
  /v1/webhooks:
    get:
      summary: List Webhooks
      description: List all Webhooks
      operationId: list-webhooks
      security:
        - auth0:
          - "read:webhooks"
    post:
      summary: Create Webhook
      description: |-
        Creates a Webhook and registers the provided URL endpoint to receive
        HTTP POST webhook messages. The endpoint for the Webhook should be able
        to accept HTTP POST requests. Please see our Webhooks documentation
        for more details.
      operationId: create-webhook
      security:
        - auth0:
          - "create:webhooks"
  /v1/webhooks/{id}:
    get:
      summary: Get Webhook
      description: Get a webhook
      operationId: get-webhook
      security:
        - auth0:
          - "read:webhooks"
    patch:
      summary: Update Webhook
      description: Update a Webhook
      operationId: update-webhook
      security:
        - auth0:
          - "update:webhooks"
    delete:
      summary: Delete Webhook
      description: Delete a Webhook
      operationId: delete-webhook
      security:
        - auth0:
          - "delete:webhooks"
  /v1/webhooks/{id}/test:
    post:
      summary: Test Webhook
      description: Execute a test on a webhook. This will send a test payload to the webhook's endpoint
      operationId: test-webhook
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages:
    get:
      summary: List Webhook Messages
      description: |-
        Lists the Webhook messages for a specific webhook. A message refers to the
        payload sent to your webhook endpoint whenever a specific event occurs.
        Each message represents a discrete event-triggered notification that
        contains relevant data related to the event.
      operationId: list-webhook-messages
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages/{messageId}:
    get:
      summary: Get Webhook Message
      description: |-
        Gets a specific Webhook Message for a specific webhook. A message refers to the
        payload sent to your webhook endpoint whenever a specific event occurs.
        Each message represents a discrete event-triggered notification that
        contains relevant data related to the event.
      operationId: get-webhook-message
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages/{messageId}/resend:
    post:
      summary: Resend Webhook Message
      description: |-
        Resend webhook request for a specific webhook. This does not resend the
        request to all of the original webhooks.
      operationId: resend-message
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages/{messageId}/attempts:
    get:
      summary: List Webhook Message Attempts
      description: Lists the attempts to send a request for a specific message for a specific webhook
      operationId: list-message-attempts
      security:
        - auth0:
          - "read:webhooks"
  /v1/webhooks/{id}/messages/{messageId}/attempts/{attemptId}:
    get:
      summary: Get Webhook Message Attempt
      description: Gets a Webhook Message Attempt for a specific message and webhook.
      operationId: get-webhook-message-attempt
      security:
        - auth0:
          - "read:webhooks"
components:
  securitySchemes:
    auth0:
      type: oauth2
      description: This API uses OAuth2 with the client credentials flow.
      flows:
        clientCredentials:
          tokenUrl: https://login.givechariot.com/oauth/token
          scopes:
            "read:webhooks": read all webhooks associated with a subscription
            "create:webhooks": create webhooks for a subscritpion
            "update:webhooks": update all webhooks associated with a subscription
            "delete:webhooks": delete webhooks associated with a subscription
    api_key:
      type: apiKey
      in: header
      name: x-chariot-api-key